### PR TITLE
Correct gfa() and apply transforms in two steps

### PR DESCRIPTION
**Pull request by suheyla2**

### CODE REVIEW

**Comment by tashrifbillah** [comment]
Have you tested this PR on old data such as `BSNIP_Baltimore`, `Szeszko` and `MRC`?

**Comment by suheyla2** [comment]
> Have you tested this PR on old data such as `BSNIP_Baltimore`, `Szeszko` and `MRC`?

yes!

**Review by tashrifbillah — APPROVED** [review]

**Comment by tashrifbillah** [comment]
TODO: Similar changes required in https://github.com/pnlbwh/multi-shell-dMRIharmonization

Closes https://github.com/pnlbwh/multi-shell-dMRIharmonization/issues/26 and https://github.com/pnlbwh/multi-shell-dMRIharmonization/issues/27

**Comment by tashrifbillah** [comment]
Test in progress ...

**Comment by tashrifbillah** [comment]
Test passed

**Comment by tashrifbillah** [comment]
Deployed everywhere ...

**Pull request merged**
